#! /bin/bash
sudo yum update
sudo yum install nginx
systemctl start nginx
sudo yum install http://rpms.remirepo.net/enterprise/remi-release-7.rpm
sudo yum --disablerepo="*" --enablerepo="remi-safe" list php[7-9][0-9].x86_64
sudo yum-config-manager --enable remi-php74
sudo yum install php php-mysqlnd php-fpm
php --version
cat >/etc/php-fpm.d/www.conf <<"EOF"
; Start a new pool named 'www'.
[www]
listen = /var/run/php-fpm/php-fpm.sock;
listen.allowed_clients = 127.0.0.1

listen.owner = nginx
listen.group = nginx
listen.mode = 0666
user = nginx
group = nginx
pm = dynamic
pm.max_children = 50
pm.start_servers = 5
pm.min_spare_servers = 5
pm.max_spare_servers = 35
slowlog = /var/log/php-fpm/www-slow.log
php_admin_value[error_log] = /var/log/php-fpm/www-error.log
php_admin_flag[log_errors] = on
php_value[session.save_handler] = files
php_value[session.save_path] = /var/lib/php/session
EOF
sudo systemctl start php-fpm
cat >/etc/nginx/conf.d/default.conf <<"EOF"
server {
    listen       80;
    server_name  server_domain_or_IP;

    root   /usr/share/nginx/html;
    index index.php index.html index.htm;

    location / {
        try_files $uri $uri/ =404;
    }
    error_page 404 /404.html;
    error_page 500 502 503 504 /50x.html;

    location = /50x.html {
        root /usr/share/nginx/html;
    }

    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_pass unix:/var/run/php-fpm/php-fpm.sock;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }
}
EOF
systemctl restart nginx
sudo chown -R nginx.nginx /usr/share/nginx/html/
cat >/usr/share/nginx/html/info.php <<"EOF"
    echo "<?php phpinfo(); ?>" >/usr/share/nginx/html/info.php
EOF
#################### supervisord ######################
udo yum install epel-release
sudo yum update
sudo yum nginx
sudo systemctl enable nginx
sudo systemctl start nginx
sudo systemctl status nginx
sudo yum update
sudo yum install epel-release
sudo yum install supervisor
#echo "[unix_http_server]" | sudo tee -a /etc/supervisord.conf
#echo "file=/tmp/supervisor.sock" | sudo tee -a /etc/supervisord.conf
#echo "chmod=0700" | sudo tee -a /etc/supervisord.conf 
#echo "[supervisord]" | sudo tee -a /etc/supervisord.conf
#echo "logfile=/var/log/supervisor/supervisord.log" | sudo tee -a /etc/supervisord.conf
#echo "pidfile=/var/run/supervisord.pid" | sudo tee -a /etc/supervisord.conf
#echo "childlogdir=/var/log/supervisor" | sudo tee -a /etc/supervisord.conf
#echo "user=root" | sudo tee -a /etc/supervisord.conf 
#echo "[rpcinterface:supervisor]" | sudo tee -a /etc/supervisord.conf
#echo "supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface" | sudo tee -a /etc/supervisord.conf 
#echo "[supervisorctl]" | sudo tee -a /etc/supervisord.conf
#echo "serverurl=unix:///tmp/supervisor.sock" | sudo tee -a /etc/supervisord.conf
echo "[inet_http_server]" | sudo tee -a /etc/supervisord.conf
echo "Port=*:9001" | sudo tee -a /etc/supervisord.conf
sudo mkdir -p /var/log/supervisor
sudo systemctl enable supervisord
sudo systemctl start supervisord
sudo systemctl status supervisord

###################################################    redis   ####################################
sudo yum update
sudo yum install epel-release
sudo yum install redis
sudo systemctl enable redis
sudo systemctl start redis
sudo yum install php-pear php-devel
sudo pecl install igbinary igbinary-devel redis
echo "extension=redis.so" | sudo tee -a /etc/php.ini
echo "session.save_handler = redis" | sudo tee -a /etc/php.ini
echo "session.save_path = “tcp://127.0.0.1:6379”" | sudo tee -a /etc/php.ini


###################################### gpung ##################################
yum update
yum install bzip2
yum install curl
curl -OL "https://gist.githubusercontent.com/simbo1905/ba3e8af9a45435db6093aea35c6150e8/raw/83561e214e36f6556fd6b1ec0a384cf28cb2debf/install-gnupg22.sh"
sudo yum install gnupg
sudo yum makecache
sudo yum -y install gnupg1
gpg --version
sudo yum install gpgme-devel
sudo yum install http://mirror.centos.org/centos/7/os/x86_64/Packages/gpgme-devel-1.3.2-5.el7.x86_64.rpm
sudo yum install php-devel
sudo pecl install gnupg
echo "extension=gnupg.so" | sudo tee -a /etc/php.ini
sudo systemctl restart php-fpm
